### ISSUE TITLE
Command line prompt problem when exit

### ISSUE THREAD

**Issue by xtreeguy** [fpereiro/clit#2]
There is a small problem with command line prompt when you are press the `Ctrl-C` keys, because there is no `\n` character in the end of the last log output line and when timer will stopped you will get something like:

```
Timer started. Press CTRL+Z to pause/resume and CTRL+C to quit.
Stopped after 00:10%my-prompt
```

instead of

```
Timer started. Press CTRL+Z to pause/resume and CTRL+C to quit.
Stopped after 00:10
%my-prompt
```

I did not fix it because I do not know what you would prefer:
- Use `\n` only on timer exit or
- Put it inside the `log` function

**Comment by fpereiro** [comment]
Hello there,

Thank you very much for your contribution!

I added the newline only on timer exit, since I like having the cursor blinking next to the time while the timer is running; if I had put the newline on the log function, after pausing the timer, the cursor wouldn't blink next to the time.

**Comment by xtreeguy** [comment]
Nice!
