### ISSUE TITLE
License

### ISSUE THREAD

**Issue by joepie91** [fpereiro/clit#3]
The code appears to be 'dedicated to the public domain', but this is not legally possible in many jurisdictions (including most of Europe). The [WTFPL](http://www.wtfpl.net/) or [CC0](https://creativecommons.org/publicdomain/zero/1.0/) would be better options, with the intended practical effect (no restrictions).

I've written some more about licensing (and this issue) is here: http://cryto.net/~joepie91/blog/2013/03/21/licensing-for-beginners/

**Comment by fpereiro** [comment]
Hi Sven!

Thank you for your thoughtful message and recommendation. I've read your article in detail and have been wondering about this issue.

My purpose for dedicating code to the public domain is twofold:
1) Let anybody use it, without any restrictions.
2) Question the need for a legal instrument to do so.

It is the second point that makes me decide against using any legal license, no matter how liberal it is.

I deem it very unlikely that anybody will find the dedication to the public domain (in lieu of CC0 or WTFPL) as a legal restriction to them using my code, in any jurisdiction.

However, if anyone has a concrete legal situation which requires me to issue a license for them using my code, I am willing to revert this stance. Until then, I'd rather do without a license.

Once again, Sven, thank you very much for your suggestion, and sorry to decline it, at least momentarily.
